'^/wp-admin$':
  to: "/wp/wp-admin/"
  regexp: true
'^/wp-admin/(.*)':
  to: "/wp/wp-admin/$1"
  regexp: true
'^/myintuition/?$':
  to: '/cost-and-aid/calculate-your-costs/myintuition-calculator/'
  regexp: true
'^/apply/nescac-admissions-practices/?$':
  to: 'https://nescac.com/sports/2020/7/14/admissions-admissions.aspx?path=prospectivestu'
  regexp: true
