name: some-site
recipe: wordpress
config:
    webroot: /web/
env_file:
    - lando.env

events:
    pre-start:
        - "echo 'creating simplesaml directories...'"
        - "/app/scripts/digitalservice/lando-create-simplesaml.sh"
        # Intall the platform.sh CLI and make sure it is up to date.
        - "echo 'installing platform CLI...'"
        - "mkdir -p /var/www/.platformsh && mkdir -p /var/www/.platformsh/bin"
        - "curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.37.1/platform.phar"
        - "chmod ug+x /var/www/.platformsh/bin/platform"
        - "cd /app && composer install"
tooling:
  platform-db-pull:
    service: appserver
    description: DESTRUCTIVE Pull the current Platform environment's DB into the current Lando project.
    cmd: "/app/scripts/digitalservice/lando-platform-db-pull.sh"
