# Change the name property to the name of your project. Suggestions is to use the name of your project in Platform,
# which is also the name/slug of your repository on gitlab
name: some-site
recipe: wordpress
config:
    webroot: web
    via: nginx
    config:
      vhosts: ./.lando/wordpress.conf
env_file:
    - lando.env

services:
  appserver:
    build:
        - "echo 'creating simplesaml directories...'"
        - "/app/scripts/digitalservice/lando-create-simplesaml.sh"
        # Intall the platform.sh CLI and make sure it is up to date.
        - "echo 'installing platform CLI...'"
        - "mkdir -p /var/www/.platformsh && mkdir -p /var/www/.platformsh/bin"
        - "curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.37.1/platform.phar"
        - "chmod ug+x /var/www/.platformsh/bin/platform"
        #- "ln -s -f /var/www/.platformsh/bin/platform /app/vendor/bin/platform"
        #- export PATH="/var/www/.platformsh/bin/platform:${PATH}"
        - "platform self-update -y"
        - "wp package install wp-cli/find-command"
        - "cd /app && composer install"
    run:
        - "./scripts/digitalservice/lando-project-set.sh"
        - "./scripts/digitalservice/lando-platform-sync.sh"

tooling:
  platform-db-pull:
    service: appserver
    description: DESTRUCTIVE Pull the current Platform environment's DB into the current Lando project.
    cmd: "/app/scripts/digitalservice/lando-platform-db-pull.sh"
  platform-db-ms-update:
    service: appserver
    description: Updates the domains in a multisite to the ones created by lando
    cmd: "php /app/scripts/digitalservice/update-multisite-db.php"
  platform-sync-all:
    service: appserver
    description: Syncs both the database and the media files (uploads) from the associated platform project.
    cmd: "/app/scripts/digitalservice/lando-platform-sync.sh y y"
  platform-media-sync:
    service: appserver
    description: Syncs the media files (uploads) from the associated platform project.
    cmd: "/app/scripts/digitalservice/lando-platform-media-sync.sh"
  platform-set-project:
    service: appserver
    description: Associates this lando project with a platform project so you don't have to select it every time.
    cmd: "/app/scripts/digitalservice/lando-project-set.sh y"
  platform:
    service: appserver
    description: Platform CLI passthru
    cmd: "platform"

# If you are setting up a WordPress multisite, you will need to uncomment the next few lines.  For each domain in your
# multisite, you will need them in the list. Please append '.lndo.info' to the end of your production domain names
# (e.g. digitalservice.missouri.edu.lndo.info) so the database update script knows how to match your production domain
# names to those in lando.
#proxy:
#    appserver_nginx:
#        - site1.missouri.edu.lndo.site
#        - site2.missouri.edu.lndo.site
#        - site3.missouri.edu.lndo.site