# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "php:7.2"

# Configuration of the build of the application.
build:
    flavor: composer

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "mysqldb:mysql"

# The size of the persistent disk of the application (in MB).
disk: !include .platform/digitalservice/disk.yaml

# The mounts that will be performed when the package is deployed.
mounts:
    "/web/wp-content/uploads": "shared:files/uploads"
    "/web/wp-content/cache": "shared:files/cache"
    '/simplesaml/cert': 'shared:files/simplesaml/cert'
    '/simplesaml/logs': 'shared:files/simplesaml/logs'
    '/simplesaml/data': 'shared:files/simplesaml/data'
    '/simplesaml/tmp': 'shared:files/simplesaml/tmp'

# The configuration of app when it is exposed to the web.
web:
  locations:
    "/":
      # The public directory of the app, relative to its root.
      root: "web"
      # The front-controller script to send non-static requests to.
      passthru: "/index.php"
      # Wordpress has multiple roots (wp-admin) so the following is required
      index:
        - "index.php"
      # The number of seconds whitelisted (static) content should be cached.
      expires: 600
      scripts: true
      allow: true
      rules:
        # Allow access to common static files.
        '\.(?i:jpe?g|gif|png|svg|bmp|ico|css|js(?:on)?|eot|ttf|woff|woff2|pdf|docx?|xlsx?|pp[st]x?|psd|odt|key|mp[2-5g]|m4[av]|og[gv]|wav|mov|wm[av]|avi|3g[p2])$':
          allow: true
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true
        '^\/wp-login.php$':
          allow: true
          scripts: true
          passthru: '/wp/wp-login.php'

    "/simplesaml":
      root: 'vendor/simplesamlphp/simplesamlphp/www'
      allow: true
      scripts: true
      index:
        - index.php
    "/wp-admin":
      root: 'web/wp/wp-admin'
      allow: true
      scripts: true
      index:
        - 'index.php'
    "/wp-includes":
      root: 'web/wp/wp-includes'
      allow: true
      scripts: true

dependencies:
  php: !include .platform/digitalservice/dependencies.php.yaml

runtime:
  extensions: !include .platform/digitalservice/runtime.extensions.yaml

# The hooks that will be performed when the package is deployed.
hooks:
    build: !include
      type: string
      path: .platform/digitalservice/hooks.build.yaml
    deploy: !include
      type: string
      path: .platform/digitalservice/hooks.deploy.yaml

variables:
  env: !include .platform/digitalservice/variables.env.yaml

# The configuration of scheduled execution.
crons: !include .platform/digitalservice/crons.yaml