# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "php:7.4"

# Configuration of the build of the application.
build:
  flavor: composer

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "mysqldb:mysql"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
  "/web/wp-content/uploads": "shared:files/uploads"
  "/web/wp-content/cache": "shared:files/cache"
  "/web/wp-content/okta": "shared:files/plugins/okta"
  "/web/.well-known/pki-validation":
    source: local
    source_path: web

# The configuration of app when it is exposed to the web.
web:
  locations: !include project/platform/web.locations.yaml

runtime:
  extensions: 
    - readline

dependencies:
  php:
    composer/composer: "^2"

# The hooks that will be performed when the package is deployed.
hooks:
    build: !include
      type: string
      path: project/platform/hooks.build.yaml
    deploy: !include
      type: string
      path: project/platform/hooks.deploy.yaml

variables:
  env: !include project/platform/variables.env.yaml
  php:
    upload_max_filesize: 128M
    memory_limit: 256M

# The configuration of scheduled execution.
crons: !include project/platform/crons.yaml