# Route file specific to multidomain multisites.
# DO NOT USE THIS FILE IF YOU ARE NOT RUNNING A MULTIDOMAIN WORDPRESS MULTISITE
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{all}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: true

        # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
        cookies: ['/^SS?ESS/', '/^SimpleSAML/', '/^wordpress_/', '/^wp-settings/']
    redirects:
        expires: 30s
        paths:
          '^/wp-admin$':
            to: '/wp-admin/'
            regexp: true

"https://www.{all}/":
    type: redirect
    to: "https://{all}/"