name: Run Maintenance
on:
  push:
    branches:
      - 'maintenance-*'
jobs:
  percy:
    uses: ./.github/workflows/percy.yml
    secrets: inherit
  cypress:
    runs-on: ubuntu-latest
    steps:
      run: npm run tests